#!/bin/bash
# ============================================================================
# setup.sh — one-command setup on macOS:
#   1. installs Homebrew + XcodeGen + Xcode command line tools if missing
#   2. creates a Python venv and installs backend dependencies
#   3. detects the Mac's Wi-Fi IP and writes it into the iOS app
#   4. starts the backend in a separate Terminal window
#   5. generates AccessMarketplace.xcodeproj and opens it in Xcode
#
# Usage:  bash setup.sh
# Then:   in Xcode pick iPhone 15 Pro Max simulator or your real iPhone → ⌘R
# ============================================================================
set -e
cd "$(dirname "$0")"

echo "==> [1/5] Checking Xcode command line tools..."
if ! xcode-select -p >/dev/null 2>&1; then
  echo "    Installing Xcode Command Line Tools (GUI prompt may appear)..."
  xcode-select --install || true
  echo "    Re-run setup.sh after the tools finish installing."
  exit 1
fi
if [ "$(uname)" != "Darwin" ]; then
  echo "This script must run on macOS."; exit 1
fi

echo "==> [2/5] Checking Homebrew..."
if ! command -v brew >/dev/null 2>&1; then
  echo "    Installing Homebrew (may ask for your password)..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv 2>/dev/null || /usr/local/bin/brew shellenv 2>/dev/null)"
fi

echo "==> [3/5] Preparing backend..."
cd backend
if [ ! -d .venv ]; then python3 -m venv .venv; fi
source .venv/bin/activate
pip install -q --upgrade pip
pip install -q -r requirements.txt
echo "    Seeding demo data + test accounts..."
python -X utf8 seed.py || echo "    (seed skipped — see message above)"
deactivate
cd ..

echo "==> [4/5] Pointing the iOS app at this Mac..."
IP="$(ipconfig getifaddr en0 2>/dev/null || true)"
[ -z "$IP" ] && IP="$(ipconfig getifaddr en1 2>/dev/null || true)"
if [ -z "$IP" ]; then
  echo "    Could not detect Wi-Fi IP — falling back to localhost (simulator only)."
  IP="localhost"
else
  echo "    Detected Mac IP: $IP (iPhone and Mac must share the same Wi-Fi)"
fi
cat > ios/AccessMarketplace/Core/ServerConfig.swift <<EOF
// ServerConfig.swift — auto-generated by setup.sh, do not edit by hand.
// Mac LAN IP so a real iPhone can reach the backend over Wi-Fi.
enum ServerConfig {
    static let apiBaseURL = "http://${IP}:8000/api"
}
EOF

echo "    Installing XcodeGen..."
brew list xcodegen >/dev/null 2>&1 || brew install xcodegen

echo "==> [5/5] Generating Xcode project..."
cd ios
rm -rf AccessMarketplace.xcodeproj
xcodegen
echo "    Starting backend in a new Terminal window..."
osascript >/dev/null 2>&1 <<EOF || echo "    (Could not open Terminal — start backend manually: cd backend && .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000)"
tell application "Terminal"
  activate
  do script "cd \"$(cd .. && pwd)\"/backend && .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000"
end tell
EOF
echo "    Opening project in Xcode..."
open AccessMarketplace.xcodeproj

echo ""
echo "============================================================"
echo " DONE"
echo " Backend:   http://${IP}:8000  (Swagger: /docs)"
echo " Admin:     admin@access.marketplace / ChangeMe-Admin-2026!"
echo ""
echo " In Xcode:"
echo "  • Simulator: pick 'iPhone 15 Pro Max' → ⌘R"
echo "  • Real device: plug in iPhone 15 Pro Max, enable"
echo "    Settings → Privacy & Security → Developer Mode,"
echo "    select your Apple ID under Signing & Capabilities → ⌘R"
echo "============================================================"
